name: wordmap

channels:
        - conda-forge
        - pypi

dependencies:
        - python==3.8
        - spacy==3.0.5
        - opentsne==0.5.1
        - scikit-learn==0.24.1
        - matplotlib==3.3.4
        - mpld3==0.5.2
        - numpy==1.19.2
        - pandas==1.2.3

        - pip:
                - requirements.txt
